package com.algotrading.app

import android.app.AlertDialog
import android.app.DatePickerDialog
import android.graphics.Color
import android.os.Bundle
import android.view.Gravity
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.util.Calendar
import java.util.Locale

class FullFnoBacktestActivity : AppCompatActivity() {
    private lateinit var tvStatus: TextView
    private lateinit var tvResults: TextView
    private lateinit var tvGapCalendar: TextView
    private lateinit var gapCalendarRows: LinearLayout
    private lateinit var etGapResultSearch: EditText
    private lateinit var btnGapResultSearch: Button
    private lateinit var replayStatus: TextView
    private lateinit var replayView: IntradayReplayView
    private lateinit var btnReplayPlay: Button
    private lateinit var btnReplayReset: Button
    private lateinit var btnStart: Button
    private lateinit var btnCancel: Button
    private lateinit var btnLoadMore: Button
    private lateinit var btnPurge: Button
    private lateinit var btnGapCalendar: Button
    private lateinit var strategyBuilder: CashFutureStrategyBuilderView
    private var jobId: String? = null
    private var nextSequence: Int? = null
    private var loading = false
    private var replayJob: Job? = null
    private var replayTradingDate: String? = null
    private var replaySymbol: String? = null
    private var replayMode: String = "CURRENT"
    private var replayContractMonth: String? = null
    private var replayFocusTimestamp: String? = null
    private var replayStrategyBindingKey: String? = null

    companion object { private const val MAX_RESULT_TEXT_CHARS = 20000 }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_full_fno_backtest)
        tvStatus = findViewById(R.id.tvFullFnoStatus); tvResults = findViewById(R.id.tvFullFnoResults); tvGapCalendar = findViewById(R.id.tvGapCalendar); gapCalendarRows = findViewById(R.id.llGapCalendarRows); etGapResultSearch = findViewById(R.id.etGapResultSearch); btnGapResultSearch = findViewById(R.id.btnGapResultSearch); replayStatus = findViewById(R.id.tvIntradayReplayStatus); replayView = findViewById(R.id.intradayReplayView)
        replayView.setTimeframeChangedListener { timeframe -> val date = replayTradingDate; val symbol = replaySymbol; if (date != null && symbol != null) loadCashFutureReplay(date, symbol, timeframe, replayMode, replayContractMonth, replayFocusTimestamp) }
        btnReplayPlay = findViewById(R.id.btnIntradayReplayPlay); btnReplayReset = findViewById(R.id.btnIntradayReplayReset); btnStart = findViewById(R.id.btnFullFnoStart); btnCancel = findViewById(R.id.btnFullFnoCancel); btnLoadMore = findViewById(R.id.btnFullFnoLoadMore); btnPurge = findViewById(R.id.btnFullFnoPurge); btnGapCalendar = findViewById(R.id.btnGapCalendar); strategyBuilder = findViewById(R.id.cashFutureStrategyBuilder)
        btnLoadMore.isEnabled = false; btnCancel.isEnabled = false; btnPurge.isEnabled = false; btnReplayPlay.isEnabled = false; btnReplayReset.isEnabled = false
        btnStart.setOnClickListener { startBacktest() }; btnCancel.setOnClickListener { cancelBacktest() }; btnLoadMore.setOnClickListener { loadNextPage() }; btnPurge.setOnClickListener { confirmPurge() }; btnGapCalendar.setOnClickListener { openGapCalendar() }; btnGapResultSearch.setOnClickListener { searchGapResults() }; btnReplayPlay.setOnClickListener { toggleReplay() }; btnReplayReset.setOnClickListener { replayJob?.cancel(); replayView.resetReplay(); btnReplayPlay.text = "PLAY ${replayView.replayIntervalSeconds()} SEC"; updateReplayStatus() }
        if (intent.getBooleanExtra("OPEN_CASH_FUTURE_CALENDAR", false)) tvStatus.post { openGapCalendar() }
    }
    private fun startBacktest() = lifecycleScope.launch(Dispatchers.IO) { if (loading) return@launch; loading = true; withContext(Dispatchers.Main) { btnStart.isEnabled = false; btnCancel.isEnabled = true; btnLoadMore.isEnabled = false; btnPurge.isEnabled = false; nextSequence = null; tvResults.text = ""; tvStatus.text = "Starting Full-F&O backtest…" }; try { val accepted = ApiService.retrofitService.startFullFnoJob(); jobId = accepted.job; pollJob(accepted.job) } catch (e: Exception) { withContext(Dispatchers.Main) { tvStatus.text = "Start failed • ${e.message ?: "API error"}"; btnStart.isEnabled = true; btnCancel.isEnabled = false } } finally { loading = false } }
    private suspend fun pollJob(id: String) { while (true) { val job = ApiService.retrofitService.fullFnoJob(id); withContext(Dispatchers.Main) { tvStatus.text = "Full-F&O: ${job.job.status.uppercase()} • ${job.job.symbols_processed}/${job.job.symbols_total} • ${job.job.progress_pct}%" }; if (job.job.status == "completed" || job.job.status == "failed" || job.job.status == "cancelled") { withContext(Dispatchers.Main) { btnCancel.isEnabled = false; btnStart.isEnabled = true; btnLoadMore.isEnabled = job.job.result_chunks > 0; btnPurge.isEnabled = true }; if (job.job.result_chunks > 0) loadNextPageInternal(id); return }; delay(1500) } }
    private fun cancelBacktest() = lifecycleScope.launch(Dispatchers.IO) { val id = jobId ?: return@launch; if (!loading) return@launch; withContext(Dispatchers.Main) { btnCancel.isEnabled = false; tvStatus.text = "Full-F&O: CANCELLING…" }; try { val response = ApiService.retrofitService.cancelFullFnoJob(id); withContext(Dispatchers.Main) { tvStatus.text = "Full-F&O: ${response.job_status.uppercase()}" } } catch (e: Exception) { withContext(Dispatchers.Main) { btnCancel.isEnabled = true; tvStatus.text = "Cancel failed • ${e.message ?: "API error"}" } } }
    private fun loadNextPage() = lifecycleScope.launch(Dispatchers.IO) { if (loading || jobId == null) return@launch; loading = true; try { loadNextPageInternal(jobId!!) } finally { loading = false } }
    private suspend fun loadNextPageInternal(id: String) { val page = ApiService.retrofitService.fullFnoResults(id, limit = 50, afterSequence = nextSequence); if (page.data.isEmpty()) { withContext(Dispatchers.Main) { btnLoadMore.isEnabled = false; tvStatus.text = "Full-F&O: no more results" }; return }; val text = buildString { page.data.forEach { chunk -> append("#${chunk.sequence}  ${chunk.symbol}\n"); append(chunk.result.toString()); append("\n────────────────────\n") } }; withContext(Dispatchers.Main) { val combined = tvResults.text.toString() + text; tvResults.text = if (combined.length <= MAX_RESULT_TEXT_CHARS) combined else "[Older results trimmed from device display to keep Android memory bounded]\n\n" + combined.takeLast(MAX_RESULT_TEXT_CHARS); nextSequence = page.next_after_sequence; btnLoadMore.isEnabled = page.next_after_sequence != null && page.data.isNotEmpty(); tvStatus.text = "Full-F&O: loaded ${page.data.size} results • total ${page.total} • next ${page.next_after_sequence ?: "END"}" } }
    private fun openGapCalendar() { val today = Calendar.getInstance(); DatePickerDialog(this, { _, year, month, day -> loadGapForDate(year, month + 1, day) }, today.get(Calendar.YEAR), today.get(Calendar.MONTH), today.get(Calendar.DAY_OF_MONTH)).show() }
    private fun loadGapForDate(year: Int, month: Int, day: Int) = lifecycleScope.launch(Dispatchers.IO) { val tradingDate = "%04d-%02d-%02d".format(year, month, day); withContext(Dispatchers.Main) { tvGapCalendar.text = "$tradingDate • loading ALL available Cash−Future paired intraday gap rankings…"; gapCalendarRows.removeAllViews() }; try { val response = ApiService.retrofitService.dateGapRanking(tradingDate, mode = "shorting", instrumentType = "STOCK", limit = 500); val prior = runCatching { ApiService.retrofitService.priorGapComparison(tradingDate, mode = "shorting", instrumentType = "STOCK", limit = 5) }.getOrNull(); val monthHighs = response.data.associate { item -> item.symbol to runCatching { ApiService.retrofitService.monthlyGapSearch(year, month, mode = "shorting", instrumentType = "STOCK", symbol = item.symbol).result }.getOrNull() }; val top = response.top; withContext(Dispatchers.Main) { tvGapCalendar.text = buildString { if (top == null) append("$tradingDate\nNo historical Cash-Future data found.") else { val topCash = top.cash_price_at_gap_high ?: top.open; val topFuture = top.future_price_at_gap_high ?: top.high; append("$tradingDate • TOP CASH-FUTURE GAP × HISTORICAL LOT\n"); append("${top.symbol} • Shorting Gap (Day High) ₹${"%.2f".format(top.gap)} • Gap×Lot ₹${"%.2f".format(top.weighted_gap)}\n"); append("Gap High Time: ${top.gap_high_timestamp ?: "-"} • Cash ₹${"%.2f".format(topCash)} • Future ₹${"%.2f".format(topFuture)} • Lot ${"%.0f".format(top.lot_size)}") }; append("\n\nPRIOR HIGHER GAPS"); if (prior == null || !prior.has_larger_prior_gap) append("\nNone — this selected date is at/above all earlier available gaps.") else prior.prior_larger.forEach { p -> append("\n${p.trading_date} • ${p.symbol} • Gap ₹${"%.2f".format(p.gap)} • Gap×Lot ₹${"%.2f".format(p.weighted_gap)}") } } }; response.data.forEach { item -> addCalendarRow(tradingDate, item, monthHighs[item.symbol]) } } catch (e: Exception) { withContext(Dispatchers.Main) { tvGapCalendar.text = "$tradingDate • Gap calendar failed • ${e.message ?: "API error"}" } } }
    private fun addCalendarRow(tradingDate: String, item: DailyGapCalendarItem, monthHigh: MonthlyGapResult?) { val row = LinearLayout(this).apply { orientation = LinearLayout.HORIZONTAL; gravity = Gravity.CENTER_VERTICAL; setPadding(8, 6, 4, 6) }; val details = TextView(this).apply { layoutParams = LinearLayout.LayoutParams(0, LinearLayout.LayoutParams.WRAP_CONTENT, 1f); setTextColor(Color.WHITE); textSize = 11f; text = buildString { append("${item.symbol}  Shorting Gap (Day High) ₹${"%.2f".format(item.gap)} × Lot ${"%.0f".format(item.lot_size)} = ₹${"%.2f".format(item.weighted_gap)}\n"); append("Gap High Time: ${item.gap_high_timestamp ?: "-"}\n"); val cashAtHigh = item.cash_price_at_gap_high ?: item.open; val futureAtHigh = item.future_price_at_gap_high ?: item.high; append("Cash/Future at Gap High: ₹${"%.2f".format(cashAtHigh)} / ₹${"%.2f".format(futureAtHigh)}\n"); if (monthHigh == null) append("Month Gap High: unavailable") else append("Month Gap High: ₹${"%.2f".format(monthHigh.gap)} • ${monthHigh.trading_date} • Gap×Lot ₹${"%.2f".format(monthHigh.gap_value)}") } }; val builder = Button(this).apply { text = "BUILD"; textSize = 10f; setOnClickListener { loadCalendarSelectionIntoBuilder(tradingDate, item) } }; val graph = Button(this).apply { text = "GRAPH"; textSize = 10f; setOnClickListener { loadIntradayReplay(tradingDate, item.symbol, "CURRENT") } }; val nextGraph = Button(this).apply { text = "NEXT"; textSize = 10f; setOnClickListener { loadIntradayReplay(tradingDate, item.symbol, "NEAR") } }; row.addView(details); row.addView(builder, LinearLayout.LayoutParams(78, 44).apply { setMargins(3, 0, 3, 0) }); row.addView(graph, LinearLayout.LayoutParams(76, 44).apply { setMargins(2, 0, 2, 0) }); row.addView(nextGraph, LinearLayout.LayoutParams(76, 44)); gapCalendarRows.addView(row) }
    private fun loadCalendarSelectionIntoBuilder(tradingDate: String, item: DailyGapCalendarItem) = lifecycleScope.launch(Dispatchers.IO) { withContext(Dispatchers.Main) { tvStatus.text = "Loading historical contracts • ${item.symbol} • $tradingDate…" }; try { val current = ApiService.retrofitService.cashFutureReplay(tradingDate, item.symbol, timeframe = "1m", mode = "CURRENT"); val near = ApiService.retrofitService.cashFutureReplay(tradingDate, item.symbol, timeframe = "1m", mode = "NEAR"); val historicalCash = item.cash_price_at_gap_high ?: item.open; val historicalFuture = item.future_price_at_gap_high ?: item.high; withContext(Dispatchers.Main) { strategyBuilder.bindHistoricalSelection(selectedSymbol = item.symbol, historicalCash = historicalCash, historicalLot = item.lot_size, selectedDate = tradingDate, historicalFuture = historicalFuture, currentContract = current.contract_month, nearContract = near.contract_month); tvStatus.text = "Cash-Future strategy loaded • ${item.symbol} • $tradingDate • Gap High ${item.gap_high_timestamp ?: "-"} • CURRENT ${current.contract_month ?: "-"} • NEAR ${near.contract_month ?: "-"}" } } catch (e: Exception) { withContext(Dispatchers.Main) { strategyBuilder.bindHistoricalSelection(item.symbol, item.cash_price_at_gap_high ?: item.open, item.lot_size, tradingDate, item.future_price_at_gap_high ?: item.high); tvStatus.text = "Builder loaded • ${item.symbol} • $tradingDate • contract lookup failed: ${e.message ?: "API error"}" } } }
    private fun addMonthlyTop10Row(item: MonthlyGapTop10Item) { val expiryDay = item.is_expiry_day; val row = LinearLayout(this).apply { orientation = LinearLayout.HORIZONTAL; gravity = Gravity.CENTER_VERTICAL; setPadding(8, 6, 4, 6); if (expiryDay) setBackgroundColor(Color.rgb(70, 0, 0)) }; val details = TextView(this).apply { layoutParams = LinearLayout.LayoutParams(0, LinearLayout.LayoutParams.WRAP_CONTENT, 1f); setTextColor(if (expiryDay) Color.RED else Color.WHITE); textSize = 11f; text = buildString { append(if (expiryDay) "🔴 EXPIRY DAY • NO TRADE\n" else "🟢 TRADEABLE • HISTORICAL OPPORTUNITY\n"); append("#${item.rank}  ${item.symbol} • Lot ${"%.0f".format(item.lot_size)}\n"); append("Month Gap High ₹${"%.2f".format(item.month_gap_high)} • Gap×Lot ₹${"%.2f".format(item.gap_value)}\n"); append("Date ${item.gap_high_date} • Time ${item.gap_high_time}\n"); append("Cash ₹${"%.2f".format(item.cash_price_at_gap_high)} • Future ₹${"%.2f".format(item.future_price_at_gap_high)}\n"); append("Historical Margin ₹${"%.2f".format(item.margin_required)}\n"); append("Charges ₹${"%.2f".format(item.charges)} • Funding ₹${"%.2f".format(item.funding_cost)}\n"); append("Net Profit ₹${"%.2f".format(item.net_profit)} • ROI ${"%.2f".format(item.roi_pct)}%\n"); append("Contract ${item.contract_month ?: "-"} • ${item.instrument_key ?: "-"}"); if (expiryDay) append("\nHistorical ranking retained • execution disabled") } }; val build = Button(this).apply { text = if (expiryDay) "NO TRADE" else "BUILD"; textSize = 9f; isEnabled = !expiryDay; setOnClickListener { loadMonthlySelectionIntoBuilder(item) } }; val graph = Button(this).apply { text = "GRAPH"; textSize = 9f; setOnClickListener { loadCashFutureReplay(item.gap_high_date, item.symbol, "1m", "CURRENT", item.contract_month, item.gap_high_timestamp) } }; val nextGraph = Button(this).apply { text = "NEXT"; textSize = 9f; setOnClickListener { loadCashFutureReplay(item.gap_high_date, item.symbol, "1m", "NEAR", null, null) } }; row.addView(details); row.addView(build, LinearLayout.LayoutParams(68, 44).apply { setMargins(2, 0, 2, 0) }); row.addView(graph, LinearLayout.LayoutParams(70, 44).apply { setMargins(2, 0, 2, 0) }); row.addView(nextGraph, LinearLayout.LayoutParams(66, 44)); gapCalendarRows.addView(row) }
    private fun loadMonthlySelectionIntoBuilder(item: MonthlyGapTop10Item) = lifecycleScope.launch(Dispatchers.IO) { withContext(Dispatchers.Main) { tvStatus.text = "Loading monthly historical contracts • ${item.symbol} • ${item.gap_high_date}…" }; try { val current = ApiService.retrofitService.cashFutureReplay(item.gap_high_date, item.symbol, contractMonth = item.contract_month, timeframe = "1m", mode = "CURRENT"); val near = ApiService.retrofitService.cashFutureReplay(item.gap_high_date, item.symbol, timeframe = "1m", mode = "NEAR"); withContext(Dispatchers.Main) { strategyBuilder.bindHistoricalSelection(selectedSymbol = item.symbol, historicalCash = item.cash_price_at_gap_high, historicalLot = item.lot_size, selectedDate = item.gap_high_date, historicalFuture = item.future_price_at_gap_high, currentContract = current.contract_month ?: item.contract_month, nearContract = near.contract_month); tvStatus.text = "Monthly strategy loaded • ${item.symbol} • ${item.gap_high_date} ${item.gap_high_time} • CURRENT ${current.contract_month ?: item.contract_month ?: "-"} • NEAR ${near.contract_month ?: "-"}" } } catch (e: Exception) { withContext(Dispatchers.Main) { strategyBuilder.bindHistoricalSelection(item.symbol, item.cash_price_at_gap_high, item.lot_size, item.gap_high_date, item.future_price_at_gap_high, item.contract_month, null); tvStatus.text = "Monthly builder loaded • ${item.symbol} • contract lookup failed: ${e.message ?: "API error"}" } } }
    private fun loadIntradayReplay(tradingDate: String, symbol: String, mode: String = "CURRENT") = loadCashFutureReplay(tradingDate, symbol, "1m", mode, null, null)
    private fun loadCashFutureReplay(tradingDate: String, symbol: String, timeframe: String, mode: String = "CURRENT", contractMonth: String? = null, focusTimestamp: String? = null) = lifecycleScope.launch(Dispatchers.IO) { replayJob?.cancel(); val bindingKey = listOf(tradingDate, symbol.uppercase(Locale.ROOT), mode, contractMonth ?: "-").joinToString("|"); withContext(Dispatchers.Main) { if (replayStrategyBindingKey != bindingKey) { replayView.clearStrategyTrades(); replayStrategyBindingKey = bindingKey } }; replayTradingDate = tradingDate; replaySymbol = symbol; replayMode = mode; replayContractMonth = contractMonth; replayFocusTimestamp = focusTimestamp; withContext(Dispatchers.Main) { replayStatus.text = "$tradingDate • $symbol • ${if (mode == "NEAR") "NEXT FUTURE" else "CURRENT FUTURE"} • loading paired $timeframe history…"; btnReplayPlay.isEnabled = false; btnReplayReset.isEnabled = false }; try { val response = ApiService.retrofitService.cashFutureReplay(tradingDate, symbol, contractMonth = contractMonth, timeframe = timeframe, mode = mode); withContext(Dispatchers.Main) { replayView.setFocusTimestamp(focusTimestamp); replayView.setCashFutureData(response.series, response.available_replay_intervals); val focusPoint = focusTimestamp?.let { ts -> response.series.firstOrNull { it.timestamp == ts } }; val focusText = focusPoint?.let { " • GAP HIGH ${it.timestamp} • Cash ₹${"%.2f".format(it.cash_price)} • Future ₹${"%.2f".format(it.future_price)} • Gap ₹${"%.2f".format(it.gap)} • Margin ₹${"%.2f".format(it.margin_required)}" } ?: ""; replayStatus.text = "$tradingDate • $symbol • ${if (mode == "NEAR") "NEXT FUTURE" else "CURRENT FUTURE"} • ${response.count} paired rows • ${response.timeframe} • intervals ${response.available_replay_intervals.joinToString(" | ")}$focusText"; btnReplayPlay.isEnabled = response.count > 0; btnReplayReset.isEnabled = response.count > 0; updateReplayStatus() } } catch (e: Exception) { withContext(Dispatchers.Main) { replayStatus.text = "$tradingDate • $symbol • ${if (mode == "NEAR") "NEXT FUTURE" else "CURRENT FUTURE"} • $timeframe replay failed • ${e.message ?: "API error"}" } } }
    private fun toggleReplay() { if (replayView.isComplete()) { replayView.resetReplay(); btnReplayPlay.text = "PLAY ${replayView.replayIntervalSeconds()} SEC"; updateReplayStatus(); return }; if (replayJob?.isActive == true) { replayJob?.cancel(); btnReplayPlay.text = "PLAY ${replayView.replayIntervalSeconds()} SEC"; return }; btnReplayPlay.text = "PAUSE"; replayJob = lifecycleScope.launch { while (true) { val hasMore = withContext(Dispatchers.Main) { replayView.stepOneMinute() }; withContext(Dispatchers.Main) { updateReplayStatus() }; if (!hasMore) break; delay(500) }; btnReplayPlay.text = "REPLAY" }
    }
    private fun updateReplayStatus() { replayStatus.text = replayStatus.text.toString().substringBefore(" • replay") + " • replay ${replayView.currentTime()}" }
    private fun searchGapResults() = lifecycleScope.launch(Dispatchers.IO) { val query = etGapResultSearch.text.toString().trim(); val normalized = query.lowercase(Locale.ROOT); val today = Calendar.getInstance(); val exactDate = Regex("^(\\d{4})-(\\d{2})-(\\d{2})$").matchEntire(query); val monthQuery = Regex("^(\\d{4})-(\\d{2})$").matchEntire(query); val monthMode = query.isBlank() || normalized.contains("month") || normalized.contains("महीना") || normalized.contains("इस महीने") || monthQuery != null; withContext(Dispatchers.Main) { btnGapResultSearch.isEnabled = false; tvResults.text = "Searching Cash-Future high gap…"; gapCalendarRows.removeAllViews() }; try { if (exactDate != null) loadGapSearchDate(exactDate.groupValues[1].toInt(), exactDate.groupValues[2].toInt(), exactDate.groupValues[3].toInt()) else if (monthMode) { val y = monthQuery?.groupValues?.get(1)?.toInt() ?: today.get(Calendar.YEAR); val m = monthQuery?.groupValues?.get(2)?.toInt()?.minus(1) ?: today.get(Calendar.MONTH); loadGapSearchMonth(y, m) } else withContext(Dispatchers.Main) { tvResults.text = "Use: this month, YYYY-MM, or YYYY-MM-DD" } } finally { withContext(Dispatchers.Main) { btnGapResultSearch.isEnabled = true } } }
    private suspend fun loadGapSearchDate(year: Int, month: Int, day: Int) { val tradingDate = "%04d-%02d-%02d".format(year, month, day); val response = ApiService.retrofitService.dateGapRanking(tradingDate, mode = "shorting", instrumentType = "STOCK", limit = 500); val top = response.top; val prior = runCatching { ApiService.retrofitService.priorGapComparison(tradingDate, mode = "shorting", instrumentType = "STOCK", limit = 5) }.getOrNull(); withContext(Dispatchers.Main) { tvResults.text = buildString { append(if (top == null) "$tradingDate\nNo historical Cash-Future data found." else formatGapResult("$tradingDate • TOP CASH-FUTURE GAP", top.symbol, top.direction, top.gap, top.gap_percent, top.weighted_gap, top.previous_close, top.open, top.high, top.low, top.close, top.lot_size)); append("\n\nPRIOR HIGHER GAPS"); if (prior == null || !prior.has_larger_prior_gap) append("\nNone found.") else prior.prior_larger.forEach { p -> append("\n${p.trading_date} • ${p.symbol} • Gap ₹${"%.2f".format(p.gap)} • Gap×Lot ₹${"%.2f".format(p.weighted_gap)}") } } } }
    private suspend fun loadGapSearchMonth(year: Int, month: Int) { val result = ApiService.retrofitService.monthlyGapTop10(year, month + 1, instrumentType = "STOCK"); withContext(Dispatchers.Main) { tvResults.text = buildString { append("%04d-%02d • MONTHLY TOP 10 CASH-FUTURE GAP\n".format(year, month + 1)); append("Each stock appears once • actual paired intraday Future−Cash maximum • Gap×historical lot\n"); append("Rank • Stock • Lot • Gap High • Gap×Lot • Date • Time • Cash • Future • Contract") }; result.data.forEach { addMonthlyTop10Row(it) }; if (result.data.isEmpty()) tvResults.append("\nNo historical Cash-Future gap data found.") }
    }
    private fun formatGapResult(title: String, symbol: String, direction: String, gap: Double, gapPercent: Double, weightedGap: Double, previousClose: Double, open: Double, high: Double, low: Double, close: Double, lotSize: Double): String = buildString { append("$title\n$symbol • $direction\nGap: ₹${"%.2f".format(gap)} (${"%.2f".format(gapPercent)}%)\nGap × Lot: ₹${"%.2f".format(weightedGap)}\nPrev Close: ₹${"%.2f".format(previousClose)}\nOpen: ₹${"%.2f".format(open)}\nHigh: ₹${"%.2f".format(high)}\nLow: ₹${"%.2f".format(low)}\nClose: ₹${"%.2f".format(close)}\nLot Size: ${"%.0f".format(lotSize)}") }
    private fun confirmPurge() { val id = jobId ?: return; AlertDialog.Builder(this).setTitle("Purge Full-F&O Results?").setMessage("This permanently deletes the durable result chunks for job $id. The compact job summary is retained.").setNegativeButton("CANCEL", null).setPositiveButton("PURGE") { _, _ -> purgeResults(id) }.show() }
    private fun purgeResults(id: String) = lifecycleScope.launch(Dispatchers.IO) { withContext(Dispatchers.Main) { btnPurge.isEnabled = false; tvStatus.text = "Full-F&O: PURGING RESULTS…" }; try { val response = ApiService.retrofitService.purgeFullFnoResults(id); withContext(Dispatchers.Main) { tvResults.text = ""; nextSequence = null; btnLoadMore.isEnabled = false; tvStatus.text = "Full-F&O: purged ${response.deleted_chunks} result chunks • summary retained" } } catch (e: Exception) { withContext(Dispatchers.Main) { btnPurge.isEnabled = true; tvStatus.text = "Purge failed • ${e.message ?: "API error"}" } } }
}
